# Generated by Django 3.2.7 on 2021-09-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('stok', models.IntegerField()),
            ],
        ),
    ]
