# Generated by Django 3.2.7 on 2021-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tiop_mesa', models.CharField(max_length=50)),
                ('pedido', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
